---
- name: Ensure the setup package is installed
  tags: setup
  yum:
    name: setup
    state: present
    update_cache: yes
  register: setup_yum

- block:
    - name: Applying aliases configuration
      template:
        src: aliases.j2
        dest: /etc/aliases
        owner: root
        group: root
        mode: 0644
      notify: newaliases

    - name: Applying env, hosts, motd, tty, and shell configurations
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: environment.j2, dest: /etc/environment, mode: '0644' }
        - { src: hostname.j2, dest: /etc/hostname, mode: '0644' }
        - { src: hosts.j2, dest: /etc/hosts, mode: '0644' }
        - { src: motd.j2, dest: /etc/motd, mode: '0644' }
        - { src: securetty.j2, dest: /etc/securetty, mode: '0600' }
        - { src: shells.j2, dest: /etc/shells, mode: '0644' }
  tags: setup
  when: setup_yum|success
...
